/* pvkerr.c */
/* ====================================================================
 * Copyright (c) 2000 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.OpenSSL.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@OpenSSL.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.OpenSSL.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

/* NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include "pvk.h"

/* BEGIN ERROR CODES */
#ifndef NO_ERR
static ERR_STRING_DATA PVK_str_functs[]=
	{
{ERR_PACK(0,PVK_F_LEND2BN,0),	"LEND2BN"},
{ERR_PACK(0,PVK_F_PVK2RSA,0),	"pvk2rsa"},
{ERR_PACK(0,PVK_F_PVK_DECRYPT,0),	"pvk_decrypt"},
{ERR_PACK(0,PVK_F_PVK_ENCRYPT,0),	"pvk_encrypt"},
{ERR_PACK(0,PVK_F_PVK_READ,0),	"pvk_read"},
{ERR_PACK(0,PVK_F_PVK_WRITE,0),	"pvk_write"},
{ERR_PACK(0,PVK_F_RSA2PVK,0),	"rsa2pvk"},
{0,NULL}
	};

static ERR_STRING_DATA PVK_str_reasons[]=
	{
{PVK_R_BAD_MAGIC_NUMBER                  ,"bad magic number"},
{PVK_R_DECRYPT_ERROR                     ,"decrypt error"},
{PVK_R_FILE_WRITE_ERROR                  ,"file write error"},
{PVK_R_HEADER_READ_ERROR                 ,"header read error"},
{PVK_R_INVALID_PRIVATE_KEY_FORMAT        ,"invalid private key format"},
{0,NULL}
	};

#endif

#ifdef PVK_LIB_NAME
static ERR_STRING_DATA PVK_lib_name[]=
        {
{0	,PVK_LIB_NAME},
{0,NULL}
	};
#endif


int PVK_lib_error_code=0;

void ERR_load_PVK_strings(void)
	{
	static int init=1;

	if (PVK_lib_error_code == 0)
		PVK_lib_error_code=ERR_get_next_error_library();

	if (init)
		{
		init=0;
#ifndef NO_ERR
		ERR_load_strings(PVK_lib_error_code,PVK_str_functs);
		ERR_load_strings(PVK_lib_error_code,PVK_str_reasons);
#endif

#ifdef PVK_LIB_NAME
		PVK_lib_name->error = ERR_PACK(PVK_lib_error_code,0,0);
		ERR_load_strings(0,PVK_lib_name);
#endif
		}
	}

void ERR_PVK_error(int function, int reason, char *file, int line)
	{
	if (PVK_lib_error_code == 0)
		PVK_lib_error_code=ERR_get_next_error_library();
	ERR_PUT_error(PVK_lib_error_code,function,reason,file,line);
	}
